/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MMT;

import java.io.IOException;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Properties;
import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.testng.annotations.Test;

import Pages.BasePage;
import Resources.TestManager;

public class Library extends TestManager {
	
	enum travellerType{
		ADULT, CHILDREN, INFANT;

	}
	
	@Test
	public static void setTest(travellerType tp){
	
	System.out.println(tp.toString());
}
	
	public static void main(String[] args) {
		setTest(travellerType.ADULT);
	}
}
